name: Release Train - Prepare Release
description: Release Train - Prepare Release
outputs:
  release-branch:
    description: "Release branch"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: composite
  steps:
    - name: "Set up Java"
      id: "set-up-java"
      uses: "actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6" # v6.0.1
      with:
        distribution: "liberica"
        java-version: "24"
    - name: Prepare Release
      id: "prepare-release"
      shell: bash
      run: |-
        echo "Prepare Release"
