# Synchronization for release branches.
#
# Requires a 'RELEASE_BRANCHES_SYNCHRONIZATION_TOKEN' secret containing a fine-grained token 
# with Contents: read-only, Workflows: read-and-write, Actions: read-and-write
#
# Looks for `.github/release-branches` in the OSS repo to sync with the commercial repo
# the file must contain a list of versions on each line.

name: "Release Branches - Synchronization"
"on":
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to sync"
        required: true
        type: string
      branch:
        description: "Branch to sync"
        required: true
        type: string
jobs:
  handle:
    name: Handle Release Branches Synchronization
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_BRANCHES_SYNCHRONIZATION_TOKEN }}
    - name: Handle Release Branches Synchronization
      run: |
        echo "Handling Release Branches Synchronization (${{ inputs.repository }} ${{ inputs.branch }})"
        git config user.name "Spring Builds"
        git config user.email "spring-builds@users.noreply.github.com"
        git remote add upstream https://github.com/${{ inputs.repository }}
        git fetch upstream ${{ inputs.branch }}
        releasebranches=`git show upstream/${{ inputs.branch }}:.github/release-branches`
        while IFS= read -r releasebranch; do
            echo "Rebasing release branch $releasebranch"
            git show-ref --verify --quiet refs/heads/release/$releasebranch || git branch release/$releasebranch upstream/${{ inputs.branch }}
            git rebase upstream/${{ inputs.branch }} release/$releasebranch
            git push --force-with-lease --force-if-includes origin release/$releasebranch
        done <<< "$releasebranches"
