name: "Release Branches - Synchronization"
"on":
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to sync"
        required: true
        type: string
      branch:
        description: "Branch to sync"
        required: true
        type: string
jobs:
  handle:
    name: Handle Release Branches Synchronization
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      actions: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Handle Release Branches Synchronization
      run: |
        echo "Handling Release Branches Synchronization (${{ inputs.repository }} ${{ inputs.branch }})"
        git config user.name "Spring Builds"
        git config user.email "spring-builds@users.noreply.github.com"
        git remote add upstream https://github.com/${{ inputs.repository }}
        git fetch upstream ${{ inputs.branch }}
        releasebranches=`git show upstream/${{ inputs.branch }}:.github/release-branches`
        while IFS= read -r releasebranch; do
            echo "Rebasing release branch $releasebranch"
            git show-ref --verify --quiet refs/heads/release/$releasebranch || git branch release/$releasebranch upstream/${{ inputs.branch }}
            git rebase upstream/${{ inputs.branch }} release/$releasebranch
            git push --force-with-lease --force-if-includes origin release/$releasebranch
        done <<< "$releasebranches"
