name: "Sync Release Branches"
"on":
  push:
    branches:
    - "main"
    - "[0-9].[0-9].x"
    - "[0-9].[0-9].[0-9].x"
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to sync"
        required: true
        type: string
      branch:
        description: "Branch to sync"
        required: true
        type: string
jobs:
  trigger:
    name: Trigger Release Branches Synchronization
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Trigger Release Branches Synchronization
      env:
        GH_TOKEN: ${{ secrets.SYNC_RELEASE_BRANCHES_TOKEN }}
      if: ${{ env.GH_TOKEN != null }}
      run: |
          echo "dispatch ${{ format('{0}-commercial', github.repository) }} ${{ github.ref_name }}"
#          gh workflow run --repo ${{ format('{0}-commercial', github.repository) }} sync-release-branches.yml
  handle:
    name: Handle Release Branches Synchronization
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Handle Release Branches Synchronization
      run: |
        echo "handle ${{ inputs.repository }} ${{ inputs.branch }}"
        git remote add upstream https://github.com/${{ inputs.repository }}
        git fetch upstream ${{ inputs.branch }}
        git config user.name "Spring Builds"
        git config user.email "spring-builds@users.noreply.github.com"
