name: Sync Release Branches
on:
  push:
    branches:
    - 'main'
    - '[0-9].[0-9].x'
    - '[0-9].[0-9].[0-9].x'
  workflow_dispatch:
    inputs:
      repository:
        description: repository to sync
        required: true
        type: string
      branch:
        description: branch to sync
        required: true
        type: string
jobs:
  trigger:
    runs-on: ubuntu-latest
    # FIXME if
    steps:
      - name: Sync Release Branches
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.SYNC_RELEASE_BRANCHES_TOKEN }}
        run: |
            echo "hello ${{ format('{0}-commercial', github.repository) }} ${{ github.ref_name }}"
#          gh workflow run --repo ${{ format('{0}-commercial', github.repository) }} sync-release-branches.yml
